services:
  - type: web
    name: ai-nids
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: WORKERS
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: security-admin@example.com
      - key: ADMIN_PASSWORD
        sync: false
